
include:
  - local: '.gitlab-ci.docker-example.yml'

variables:
  CI_DEBUG_TRACE: "true"
  TRACE: "true"
  CUSTOM_CA_CERTS: "$CI_SERVER_TLS_CA_FILE"
  ADAPTIVE_PIPELINE_DISABLED: "true"
  
  DEFAULT_CA_CERTS: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    
  # cosign auth for key=gitlab://
  GITLAB_HOST: "${CI_SERVER_URL}"
  GITLAB_TOKEN: "${SIGN_TOKEN}"
  