
include:
  - local: '.gitlab-ci.docker-example.yml'
  - component: $CI_SERVER_FQDN/library/cicd/auto-gitlab/auto-release@main

variables:
  CI_DEBUG_TRACE: "false"
  CUSTOM_CA_CERTS: "$CI_SERVER_TLS_CA_FILE"
  ADAPTIVE_PIPELINE_DISABLED: "true"
    
  # cosign auth for key=gitlab://
  GITLAB_HOST: "${CI_SERVER_URL}"
  GITLAB_TOKEN: "${SIGN_TOKEN}"
  
.auto-gitlab:auto-core:public:needs:
  - job: docker-publish
  - job: docker-hadolint
  - job: ci-remote-exec:docker-healthcheck:core
  - job: docker-sbom
  - job: docker-trivy
  - job: sign:oci-cosign:core
  - job: mirroring:oci-repository:core


.utils:toolkit:shared:auto-release-RELEASE-md:
  - docker_image="${docker_image/$CI_REGISTRY/gitlab-registry.fizn.ru}"
  - |
    cat > RELEASE.md <<EOF
    # Release ${CI_COMMIT_TAG}
      
    [Перейти к последнему релизу](${CI_PROJECT_URL}/-/releases/permalink/latest)
    
    ---
    
    ## OCI образ
    
    ### Текущий (tag: ${CI_COMMIT_TAG})
    \`\`\`bash
    docker pull ${docker_image}
    \`\`\`
      
    ### Последний стабильный
    \`\`\`bash
    docker pull ${docker_image%:*}:latest
    \`\`\`
    
    ---
    
    ## Зеркало (GHCR)
    
    ### Текущий
    \`\`\`bash
    docker pull ghcr.io/fzen475/tbc-docker:${docker_tag}
    \`\`\`
      
    ### Последний стабильный
    \`\`\`bash
    docker pull ghcr.io/fzen475/tbc-docker:latest
    \`\`\`
    
    ---
    
    ## Примечание
    - Теги `latest` и `${docker_tag}` могут обновляться независимо
    - Для продакшена рекомендуется фиксировать конкретный tag
      
    EOF